### ISSUE TITLE
Error editing profile after new registration

### ISSUE THREAD

**Issue by kreativmind** [goalgorilla/open_social#11] opened 2016-08-21 14:53 UTC
I created a test user on my site. After successfully registering and confirming the email, I click on the pencil icon to edit profile and fill in the details. When I click Save, it brings me to page mysite.com/user/3/profile and displays the following message on a blank white space page:
The website encountered an unexpected error. Please try again later.

Also, I am not sure why it skipped to user 3 when I only have admin account and the test account I created, so it should be user/2/profile, correct?

Any ideas?

**Comment by ronaldtebrake** [comment] 2016-08-24 14:30
Hi @kreativmind,

Regarding user 3, this is strange but by design, see: https://www.drupal.org/node/2542080 for more info. 
About the error, that is probably due to an issue fixed in: https://www.drupal.org/node/2619878

We have fixed it in the new alpha 7 release, which is available. 

I would kindly suggest to use our drupal.org issue queue list if there is still anything wrong, this would help us keep issues centralised.

Thanks,

Ronald

**Closed by ronaldtebrake** 2016-08-24 14:30 UTC

**Comment by kreativmind** [comment] 2016-08-25 17:58
Posted this yesterday.
Trying to upgrade from alpha 6 to 7 and get the following message when running update.php

Unresolved dependency group_core_comments (Missing)

Any help is appreciated please. Thanks!

https://www.drupal.org/node/2789721
